POST    http://localhost:5000/products
Content-Type: application/json

{
 "name":"yaaseensed",
 "description":"something",
 "price":"40",
 "img": "img",
 
}

###

PATCH  http://localhost:5000/products/621601443908e33e4a1764ca
Content-Type: application/json
{
    "name":"change"
}
###
DELETE   http://localhost:5000/products
