GET     http://localhost:5000/products
Content-Type: application/json

# {
#  "name":"yaaseensed",
#  "description":"something",
#  "price":"40",
#  "img": "img",
 
# }

###

GET   http://localhost:5000/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjFjNzViMWYyMzljMTBjYTAwN2M2YjciLCJjYXJ0IjpbXSwiaWF0IjoxNjQ2MDU2ODg3LCJleHAiOjE2NDYxNDMyODd9.XfbLmKzKwYmEUtzIci2q1OlpPnST3L9YC1GNmTYZxf4
###
DELETE   http://localhost:5000/cart/621608f39b0674a596f233b2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjFjNzViMWYyMzljMTBjYTAwN2M2YjciLCJjYXJ0IjpbXSwiaWF0IjoxNjQ2MDU2MTEzLCJleHAiOjE2NDYxNDI1MTN9.4WrmowFr7thUkfHrU7E5UoWZWdvdRc9QTcF3DU7diEw