GET  http://localhost:5000/products
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjFjNzViMWYyMzljMTBjYTAwN2M2YjciLCJpYXQiOjE2NDYwMzY5MzAsImV4cCI6MTY0NjEyMzMzMH0.ceZ0AKEcN-Rs8JlO5MYDjs5SB5vXGDN3r9YUusMcWNU


###
POST    http://localhost:5000/users/signin
Content-Type: application/json

{
    "name":"yaaseendavidsasawe",
    "password":"madshit"
}